name: aice
description: A new Flutter project.

publish_to: "none"

version: 7.0.4+12

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  image_picker: ^0.8.6
  flutter_svg: ^1.1.6
  intl: ^0.18.1
  device_preview: ^1.1.0
  collection: ^1.16.0
  http: ^0.13.5
  meta: ^1.8.0
  shared_preferences: ^2.0.17
  geolocator: ^9.0.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
